server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  cloud:
    config:
      server:
        native:
          search-locations: file:///E:/Wonsik/Programming/study/inflearn/spring-cloud-msa/git-local-repo
        git:
#          uri: file://E:\Wonsik\Programming\study\inflearn\spring-cloud-msa\git-local-repo
          uri: https://github.com/wonsakku/spring-cloud-config

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh

