server:
#  port: 8081
  port: 0

spring:
  application:
    name: my-first-service

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
#    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka

